### PR TITLE
Rcu 90 change password validation

### PR DESCRIPTION
**Pull request by nberard**

### CODE REVIEW

**Comment by lrocheWB** [comment]
Jenkins test this please

**Comment by lrocheWB** [comment]
Jenkins test this please

**Comment by lrocheWB** [comment]
Jenkins test this please

**Comment by lrocheWB** [comment]
Jenkins test this please

**Comment by nberard** [comment]
test this please

**Comment by nberard** [comment]
#https://github.com/CanalTP/NMM/pull/226

**Comment by nberard** [comment]
test this please

**Comment by nberard** [comment]
test this

**Comment by nberard** [comment]
test this

**Comment by nberard** [comment]
re test this please

**Comment by Netmisa** [comment]
Work for me :+1:

**Pull request merged**
